version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            database: musicracy
            connector: postgres
            host: host.docker.internal
            port: 5432
            user: panchicore
            password:
